spring:
  datasource:
    url: jdbc:mysql://localhost:3306/c_h?remarks=true&useInformationSchema=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      connection-test-query: SELECT 1 #用于测试连接是否有效的查询语句
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: MyAppHikariCP
      initialization-fail-timeout: 10000


  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 0
        max-wait: 10000
        max-active: 8
        max-idle: 8
    database: 11

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


